version: "3.10"

services:
  app:
    build: .
    container_name: hr_bot
    entrypoint: ./boot.sh
    env_file:
      - .env_docker
    ports:
      - 5000:5000
    expose:
      - 5000
    depends_on:
      - db

  db:
    image: postgres:13.3-alpine
    container_name: hr_bot_db
    env_file:
      - .env_docker
    ports:
      - 5432:5432
    expose:
      - 5432

  bot:
    build: .
    container_name: hr_bot_telegrambot
    restart: always
    command: python tgbot/tgbot.py
    env_file:
      - .env_docker
    depends_on:
      - app