"""empty message

Revision ID: 6edcb4004eef
Revises: 5306f6540ba4
Create Date: 2022-06-14 23:54:21.968447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6edcb4004eef'
down_revision = '5306f6540ba4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('employee_employee_data_id_fkey', 'employee', type_='foreignkey')
    op.drop_column('employee', 'employee_data_id')
    op.add_column('employee_data', sa.Column('employee_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'employee_data', 'employee_data', ['employee_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employee_data', type_='foreignkey')
    op.drop_column('employee_data', 'employee_id')
    op.add_column('employee', sa.Column('employee_data_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('employee_employee_data_id_fkey', 'employee', 'employee_data', ['employee_data_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
