"""empty message

Revision ID: 85df9c2dc258
Revises: 
Create Date: 2022-07-14 15:07:36.157891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85df9c2dc258'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('programmer_level', sa.String(length=10), nullable=True))
    op.add_column('employee', sa.Column('project_end_date', sa.Date(), nullable=True))
    op.create_index(op.f('ix_employee_programmer_level'), 'employee', ['programmer_level'], unique=False)
    op.create_index(op.f('ix_employee_project_end_date'), 'employee', ['project_end_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employee_project_end_date'), table_name='employee')
    op.drop_index(op.f('ix_employee_programmer_level'), table_name='employee')
    op.drop_column('employee', 'project_end_date')
    op.drop_column('employee', 'programmer_level')
    # ### end Alembic commands ###
