"""empty message

Revision ID: a373ad0a022c
Revises: 95abd2805e26
Create Date: 2022-07-11 13:51:09.801094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a373ad0a022c'
down_revision = '95abd2805e26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('programmer_level', sa.String(length=10), nullable=True))
    op.add_column('employee', sa.Column('project_end_date', sa.Date(), nullable=True))
    op.create_index(op.f('ix_employee_nickname'), 'employee', ['nickname'], unique=False)
    op.create_index(op.f('ix_employee_programmer_level'), 'employee', ['programmer_level'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employee_programmer_level'), table_name='employee')
    op.drop_index(op.f('ix_employee_nickname'), table_name='employee')
    op.drop_column('employee', 'project_end_date')
    op.drop_column('employee', 'programmer_level')
    # ### end Alembic commands ###
