"""empty message

Revision ID: ee991f75d522
Revises: 
Create Date: 2022-06-29 21:47:10.830064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee991f75d522'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('main_technology', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_last_name'), 'employee', ['last_name'], unique=False)
    op.create_index(op.f('ix_employee_main_technology'), 'employee', ['main_technology'], unique=False)
    op.create_index(op.f('ix_employee_name'), 'employee', ['name'], unique=False)
    op.create_table('manager',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manager_email'), 'manager', ['email'], unique=True)
    op.create_table('employee_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cv', sa.Text(), nullable=True),
    sa.Column('additional_data', sa.Text(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee_data')
    op.drop_index(op.f('ix_manager_email'), table_name='manager')
    op.drop_table('manager')
    op.drop_index(op.f('ix_employee_name'), table_name='employee')
    op.drop_index(op.f('ix_employee_main_technology'), table_name='employee')
    op.drop_index(op.f('ix_employee_last_name'), table_name='employee')
    op.drop_table('employee')
    # ### end Alembic commands ###
